### PR TITLE
Remove size workflow

### PR DESCRIPTION
**Pull request by stramel**
Removes the size workflow as it isn't useful for forks. 

Also, slipped in renaming `src/hooks.tsx` to `src/hooks.ts`, I can revert this if you want.

### CODE REVIEW

**Comment by Buuntu** [comment]
Looks like there are merge conflicts

**Comment by Buuntu** [comment]
I might add you as a collaborator since you've been contributing so much, what are your thoughts?  At the very least it'll make it easier to not have to work from forks.

**Comment by stramel** [comment]
@Buuntu I'd be open to it. I generally try not to merge anything on repos that I'm a collaborator for but try to help out where I can.

**Comment by Buuntu** [comment]
Yeah I put a constraint that it requires 1 approval from a code owner, so should be good.

**Pull request merged**
